# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/ee2498db-e023-4ce3-bfab-915fff49fb0d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b2f449c3-abf7-4163-8e30-03a3c05c5fba".device = "/dev/disk/by-uuid/b2f449c3-abf7-4163-8e30-03a3c05c5fba";

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/20BF-2B1C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/34f9ae78-9c5e-4a28-af57-8c8cc13624d8"; }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
