require('hop').setup()

local hop = require('hop')
local directions = require('hop.hint').HintDirection
vim.keymap.set('', 'fl', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, {remap=true})
vim.keymap.set('', 'FL', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, {remap=true})
vim.keymap.set('', 'tl', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true , hint_offset = -1 })
end, {remap=true})
vim.keymap.set('', 'TL', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true , hint_offset = 1 })
end, {remap=true})
vim.keymap.set('', 'fa', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false })
end, {remap=true})
vim.keymap.set('', 'FA', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false })
end, {remap=true})
vim.keymap.set('', 'ta', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false, hint_offset = -1 })
end, {remap=true})
vim.keymap.set('', 'TA', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false, hint_offset = 1 })
end, {remap=true})

-- Window movement mapings
vim.keymap.set("n", "wh", "<c-w>h", { noremap = true })
vim.keymap.set("n", "wj", "<c-w>j", { noremap = true })
vim.keymap.set("n", "wk", "<c-w>k", { noremap = true })
vim.keymap.set("n", "wl", "<c-w>l", { noremap = true })
vim.keymap.set("n", "wv", "<c-w>v", { noremap = true })
vim.keymap.set("n", "ws", "<c-w>s", { noremap = true })

-- Unmap default window movement mapings
vim.keymap.set("n", "<c-w>h", "", { noremap = true })
vim.keymap.set("n", "<c-w>j", "", { noremap = true })
vim.keymap.set("n", "<c-w>k", "", { noremap = true })
vim.keymap.set("n", "<c-w>l", "", { noremap = true })
vim.keymap.set("n", "<c-w>v", "", { noremap = true })
vim.keymap.set("n", "<c-w>s", "", { noremap = true })
