require('hop').setup()

local hop = require('hop')
local directions = require('hop.hint').HintDirection
vim.keymap.set('', 'fl', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, {remap=true})
vim.keymap.set('', 'FL', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, {remap=true})
vim.keymap.set('', 'tl', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true , hint_offset = -1 })
end, {remap=true})
vim.keymap.set('', 'TL', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true , hint_offset = 1 })
end, {remap=true})
vim.keymap.set('', 'fa', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false })
end, {remap=true})
vim.keymap.set('', 'FA', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false })
end, {remap=true})
vim.keymap.set('', 'ta', function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = false, hint_offset = -1 })
end, {remap=true})
vim.keymap.set('', 'TA', function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = false, hint_offset = 1 })
end, {remap=true})

-- Window movement mapings
vim.keymap.set("n", "<leader>wh", "<c-w>h", { noremap = true })
vim.keymap.set("n", "<leader>wj", "<c-w>j", { noremap = true })
vim.keymap.set("n", "<leader>wk", "<c-w>k", { noremap = true })
vim.keymap.set("n", "<leader>wl", "<c-w>l", { noremap = true })
vim.keymap.set("n", "<leader>wv", "<c-w>v", { noremap = true })
vim.keymap.set("n", "<leader>ws", "<c-w>s", { noremap = true })

-- Unmap default window movement mapings
vim.keymap.set("n", "<c-w>h", "", { noremap = true })
vim.keymap.set("n", "<c-w>j", "", { noremap = true })
vim.keymap.set("n", "<c-w>k", "", { noremap = true })
vim.keymap.set("n", "<c-w>l", "", { noremap = true })
vim.keymap.set("n", "<c-w>v", "", { noremap = true })
vim.keymap.set("n", "<c-w>s", "", { noremap = true })

-- Window save/quit mapping
vim.keymap.set("n", "<leader>ww", "<cmd>:w<cr>", { silent = true })
vim.keymap.set("n", "<leader>w<S-q><S-q>", "<cmd>:q<cr>", { silent = true })
vim.keymap.set("n", "<leader>w<S-q>*", "<cmd>:qa<cr>", { silent = true })

