name: sum-astro-nvim-update
on:
  workflow_dispatch: # allows manual triggering
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Sum AstroNvim"
          pr-labels: |
            dependencies
            automated
          inputs: sum-astro-nvim
